spring:
  application:
    name: DawnPic
  datasource:
    url: jdbc:mysql://localhost:3306/dawn_pic
    username: hanyujie
    password: 123456

  servlet:
    multipart:
      enabled: true

server:
  port: 8080
  forward-headers-strategy: native

mybatis:
  type-handlers-package: com.hanyujie.dawnpic.mapper.typeHandler

logging:
  level:
    com:
      hanyujie:
        dawnpic:
          mapper: TRACE
