spring:
  application:
    name: DawnPic

#  datasource:
#    url: jdbc:mysql://localhost:3306/dawn_pic
#    username: hanyujie
#    password: 123456
#    driver-class-name: com.mysql.cj.jdbc.Driver

  datasource:
    url: jdbc:p6spy:mysql://localhost:3306/dawn_pic
    username: hanyujie
    password: 123456
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver

  servlet:
      multipart:
        enabled: true

  security:
    user:
      name: hanyujie
      password: 123456
      roles: ADMIN

mybatis-plus:
  type-handlers-package: com.hanyujie.dawnpic.mapper.typeHandler

server:
  port: 8080
  forward-headers-strategy: native

jwt:
  secret: 3c588b9e-7834-4ff6-8269-78551b6c874b
  expiration: 2_592_000_000

#debug: true

logging:
  level:
    com:
      hanyujie:
        dawnpic:
          mapper: TRACE

---

spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:p6spy:mysql://localhost:3306/dawn_pic
    username: hanyujie
    password: 123456
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver

logging:
  level:
    com:
      hanyujie:
        dawnpic:
          mapper: TRACE

debug: true
