spring:
  application:
    name: DawnPic
#  datasource:
#    url: jdbc:h2:file:./picData;AUTO_RECONNECT=TRUE;AUTO_SERVER=TRUE
#    driver-class-name: org.h2.Driver
#    username:
#    password:
#  h2:
#    console:
#      enabled: true
#      path: /h2-console

  datasource:
    url: jdbc:mysql://localhost:3306/dawn_pic
    username: hanyujie
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  servlet:
      multipart:
        enabled: true

#  web:
#    resources:
#      static-locations: classpath:/static


server:
  port: 8080
  forward-headers-strategy: native

mybatis:
  type-handlers-package: com.hanyujie.dawnpic.mapper.typeHandler

logging:
  level:
    com:
      hanyujie:
        dawnpic:
          mapper: TRACE

#debug: true
