spring:
  application:
    name: DawnPic

  datasource:
    url: jdbc:mysql://localhost:3306/dawn_pic
    username: hanyujie
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  servlet:
      multipart:
        enabled: true

mybatis-plus:
  type-handlers-package: com.hanyujie.dawnpic.mapper.typeHandler

server:
  port: 8080
  forward-headers-strategy: native

---

spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:p6spy:mysql://localhost:3306/dawn_pic
    username: hanyujie
    password: 123456
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver

logging:
  level:
    com:
      hanyujie:
        dawnpic:
          mapper: TRACE

debug: true
