name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package deploy

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Install Github CLI
        run: sudo apt-get install gh -y

      - name: Upload assets to release
        run: |
          tag_name=${{ github.ref }}
          tag_name=${tag_name#refs/tags/}
          for file in ${{ github.workspace }}/maven-repo/com/hanyujie/DawnPic/**/*; do
            echo "Uploading $file..."
            gh release upload "$tag_name" "$file"
          done
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
